name: Swift CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: macos-15
    if: false
    steps:
      - uses: actions/checkout@v4
      - run: swift build -v
      - run: swift test -v
